"""done

Revision ID: 12d5f9061126
Revises: 
Create Date: 2024-10-08 14:58:25.631683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12d5f9061126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consortium_applications', schema=None) as batch_op:
        batch_op.drop_column('annual_budget')
        batch_op.drop_column('membership_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consortium_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membership_type', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('annual_budget', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
