"""Add user_id to Agency model

Revision ID: 2c5072800f26
Revises: 38ee0b06456e
Create Date: 2024-10-05 13:28:14.209674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5072800f26'
down_revision = '38ee0b06456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_account_administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_registration_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('agency_registration_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_position', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('hq_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_state', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_zip_code', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_account_administrator', schema=None) as batch_op:
        batch_op.drop_column('hq_zip_code')
        batch_op.drop_column('hq_country')
        batch_op.drop_column('hq_state')
        batch_op.drop_column('hq_city')
        batch_op.drop_column('hq_address')
        batch_op.drop_column('hq_email')
        batch_op.drop_column('hq_position')
        batch_op.drop_column('hq_name')
        batch_op.drop_column('agency_registration_number')
        batch_op.drop_column('agency_registration_date')

    # ### end Alembic commands ###
