"""Add user_id to Agency model

Revision ID: 38ee0b06456e
Revises: 
Create Date: 2024-10-05 13:24:57.160023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ee0b06456e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_account_administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('member_email', sa.String(length=100), nullable=False))
        batch_op.drop_column('agency_registration_date')
        batch_op.drop_column('hq_email')
        batch_op.drop_column('hq_state')
        batch_op.drop_column('hq_name')
        batch_op.drop_column('hq_position')
        batch_op.drop_column('agency_registration_number')
        batch_op.drop_column('hq_city')
        batch_op.drop_column('hq_country')
        batch_op.drop_column('hq_address')
        batch_op.drop_column('hq_zip_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member_account_administrator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hq_zip_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('hq_address', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('hq_country', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_city', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('agency_registration_number', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_position', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_state', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('hq_email', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('agency_registration_date', sa.DATE(), nullable=False))
        batch_op.drop_column('member_email')
        batch_op.drop_column('member_name')

    # ### end Alembic commands ###
