"""init

Revision ID: be6dfa07a928
Revises: 
Create Date: 2025-01-29 21:12:27.971627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6dfa07a928'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('acronym', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mission_statement', sa.Text(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('is_ngo', sa.Boolean(), nullable=False),
    sa.Column('years_operational', sa.Integer(), nullable=False),
    sa.Column('reason_for_joining', sa.Text(), nullable=False),
    sa.Column('willing_to_participate', sa.Boolean(), nullable=False),
    sa.Column('commitment_to_principles', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_agency_user', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=129), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], name='fk_user_agency', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('board_director',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('clan', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consortium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('active_year', sa.String(length=4), nullable=False),
    sa.Column('partner_ngos', sa.Text(), nullable=False),
    sa.Column('international_staff', sa.Integer(), nullable=False),
    sa.Column('national_staff', sa.Integer(), nullable=False),
    sa.Column('program_plans', sa.Text(), nullable=False),
    sa.Column('main_donors', sa.Text(), nullable=False),
    sa.Column('annual_budget', sa.String(length=20), nullable=False),
    sa.Column('membership_type', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consortium_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('additional_accounts', sa.Integer(), nullable=False),
    sa.Column('mailing_list', sa.Text(), nullable=True),
    sa.Column('email_copy', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consortium_member_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email_address', sa.String(length=100), nullable=False),
    sa.Column('additional_accounts', sa.Integer(), nullable=False),
    sa.Column('mailing_list', sa.Text(), nullable=True),
    sa.Column('email_copy', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('registration_certificate', sa.String(length=255), nullable=False),
    sa.Column('agency_profile', sa.String(length=255), nullable=False),
    sa.Column('audit_report', sa.String(length=255), nullable=False),
    sa.Column('ngo_consortium_mandate', sa.String(length=255), nullable=False),
    sa.Column('icrc_code_of_conduct', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('founder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('clan', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('key_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contact', sa.String(length=100), nullable=False),
    sa.Column('clan', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('logout_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_account_administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_name', sa.String(length=100), nullable=False),
    sa.Column('member_email', sa.String(length=100), nullable=False),
    sa.Column('agency_registration_date', sa.Date(), nullable=False),
    sa.Column('agency_registration_number', sa.String(length=100), nullable=True),
    sa.Column('hq_name', sa.String(length=100), nullable=False),
    sa.Column('hq_position', sa.String(length=100), nullable=False),
    sa.Column('hq_email', sa.String(length=100), nullable=False),
    sa.Column('hq_address', sa.String(length=200), nullable=False),
    sa.Column('hq_city', sa.String(length=100), nullable=False),
    sa.Column('hq_state', sa.String(length=100), nullable=False),
    sa.Column('hq_country', sa.String(length=100), nullable=False),
    sa.Column('hq_telephone', sa.String(length=20), nullable=False),
    sa.Column('hq_telephone2', sa.String(length=20), nullable=True),
    sa.Column('hq_fax', sa.String(length=20), nullable=True),
    sa.Column('regional_same_as_hq', sa.Boolean(), nullable=True),
    sa.Column('regional_name', sa.String(length=100), nullable=True),
    sa.Column('regional_position', sa.String(length=100), nullable=True),
    sa.Column('regional_email', sa.String(length=100), nullable=True),
    sa.Column('regional_address', sa.String(length=200), nullable=True),
    sa.Column('regional_city', sa.String(length=100), nullable=True),
    sa.Column('regional_state', sa.String(length=100), nullable=True),
    sa.Column('regional_country', sa.String(length=100), nullable=True),
    sa.Column('regional_telephone', sa.String(length=20), nullable=True),
    sa.Column('regional_telephone2', sa.String(length=20), nullable=True),
    sa.Column('regional_fax', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unique_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_actions')
    op.drop_table('unique_documents')
    op.drop_table('member_account_administrator')
    op.drop_table('login_history')
    op.drop_table('key_staff')
    op.drop_table('founder')
    op.drop_table('document_uploads')
    op.drop_table('consortium_member_applications')
    op.drop_table('consortium_applications')
    op.drop_table('consortium')
    op.drop_table('board_director')
    op.drop_table('users')
    op.drop_table('agencies')
    # ### end Alembic commands ###
