"""Added consortiumMemberApplication

Revision ID: f05b6757c19e
Revises: 4579046a11f3
Create Date: 2024-10-09 21:08:49.347229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f05b6757c19e'
down_revision = '4579046a11f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consortium_applications', schema=None) as batch_op:
        batch_op.drop_column('documents')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consortium_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documents', sqlite.JSON(), nullable=True))

    # ### end Alembic commands ###
